name: MineIt
main: com.rogermiranda1000.mineit.MineIt
version: 0.9.8
author: rogermiranda1000
softdepend: [Multiverse-Core]
commands:
  mineit:
    description: Create mines
    usage: /<command>
permissions:
  mineit.create:
    description: Create mines
    default: op
  mineit.remove:
    description: Remove mines
    default: op
  mineit.start:
    description: Starts a mine
    default: op
  mineit.stop:
    description: Stops a mine
    default: op
  mineit.open:
    description: Open the MineIt inventory
    default: op
  mineit.stagelimit:
    description: Change the mine's stage limit
    default: op
  mineit.mine.all:
    description: Mine in all the mines
    default: true
  mineit.reset:
    description: Set all the mine blocks to bedrock
    default: op