name: MineIt
main: com.rogermiranda1000.mineit.MineIt
version: 1.1.4
author: rogermiranda1000
api-version: 1.13
softdepend: [Multiverse-Core]
commands:
  mineit:
    description: Create mines
    usage: /<command>
permissions:
  mineit.create:
    description: Create mines
    default: op
  mineit.remove:
    description: Remove mines
    default: op
  mineit.state:
    description: Starts/stops a mine
    default: op
  mineit.open:
    description: Open the MineIt inventory
    default: op
  mineit.stagelimit:
    description: Change the mine's stage limit
    default: op
  mineit.time:
    description: Change the mine's time
    default: op
  mineit.mine.all:
    description: Mine in all the mines
    default: true
  mineit.reset:
    description: Set all the mine blocks to bedrock
    default: op