name: Tests
run-name: Running integration tests on ${{ github.ref }}

on:
  pull_request:
    branches: master
    types:
      - opened

jobs:
  build:
    runs-on: watchwolf
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build
        run: mvn --batch-mode -DskipTests=true package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
