name: Tests
run-name: Running integration tests on ${{ github.ref }}

on:
  push: # temporal debug
  pull_request:
    branches: dev
    types:
      - opened

jobs:
  build:
    runs-on: watchwolf
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download private files
        run: |
          mkdir lib
          wget -q -O lib/VersionController.jar https://github.com/rogermiranda1000/Spigot-VersionController/releases/latest/download/VersionController.jar
          wget -q -O lib/MineableGems.jar https://api.spiget.org/v2/resources/83807/download
          wget -q -O lib/watchwolf-tester-0.2.1.jar https://watchwolf.dev/tester-versions/watchwolf-tester-0.2.1.jar
          wget -q -O lib/spigot-1.16.5.jar https://cdn.getbukkit.org/spigot/spigot-1.16.5.jar

      - name: Build
        run: mvn --batch-mode -DskipTests=true package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -Dtest=!MineItWithWorldGuardShould test

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nightly
          path: ./src/test/main/resources/recordings/
          retention-days: 4

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
